extends RefCounted

const ENABLED_KEY: StringName = &"enabled"
const SPECIES_KEY: StringName = &"species"

var _data: GameData = null

const GEN1_LABELS: Array[String] = [
	"BULBASAUR",
	"IVYSAUR",
	"VENUSAUR",
	"CHARMANDER",
	"CHARMELEON",
	"CHARIZARD",
	"SQUIRTLE",
	"WARTORTLE",
	"BLASTOISE",
	"CATERPIE",
	"METAPOD",
	"BUTTERFREE",
	"WEEDLE",
	"KAKUNA",
	"BEEDRILL",
	"PIDGEY",
	"PIDGEOTTO",
	"PIDGEOT",
	"RATTATA",
	"RATICATE",
	"SPEAROW",
	"FEAROW",
	"EKANS",
	"ARBOK",
	"PIKACHU",
	"RAICHU",
	"SANDSHREW",
	"SANDSLASH",
	"NIDORAN♀",
	"NIDORINA",
	"NIDOQUEEN",
	"NIDORAN♂",
	"NIDORINO",
	"NIDOKING",
	"CLEFAIRY",
	"CLEFABLE",
	"VULPIX",
	"NINETALES",
	"JIGGLYPUFF",
	"WIGGLYTUFF",
	"ZUBAT",
	"GOLBAT",
	"ODDISH",
	"GLOOM",
	"VILEPLUME",
	"PARAS",
	"PARASECT",
	"VENONAT",
	"VENOMOTH",
	"DIGLETT",
	"DUGTRIO",
	"MEOWTH",
	"PERSIAN",
	"PSYDUCK",
	"GOLDUCK",
	"MANKEY",
	"PRIMEAPE",
	"GROWLITHE",
	"ARCANINE",
	"POLIWAG",
	"POLIWHIRL",
	"POLIWRATH",
	"ABRA",
	"KADABRA",
	"ALAKAZAM",
	"MACHOP",
	"MACHOKE",
	"MACHAMP",
	"BELLSPROUT",
	"WEEPINBELL",
	"VICTREEBEL",
	"TENTACOOL",
	"TENTACRUEL",
	"GEODUDE",
	"GRAVELER",
	"GOLEM",
	"PONYTA",
	"RAPIDASH",
	"SLOWPOKE",
	"SLOWBRO",
	"MAGNEMITE",
	"MAGNETON",
	"FARFETCH'D",
	"DODUO",
	"DODRIO",
	"SEEL",
	"DEWGONG",
	"GRIMER",
	"MUK",
	"SHELLDER",
	"CLOYSTER",
	"GASTLY",
	"HAUNTER",
	"GENGAR",
	"ONIX",
	"DROWZEE",
	"HYPNO",
	"KRABBY",
	"KINGLER",
	"VOLTORB",
	"ELECTRODE",
	"EXEGGCUTE",
	"EXEGGUTOR",
	"CUBONE",
	"MAROWAK",
	"HITMONLEE",
	"HITMONCHAN",
	"LICKITUNG",
	"KOFFING",
	"WEEZING",
	"RHYHORN",
	"RHYDON",
	"CHANSEY",
	"TANGELA",
	"KANGASKHAN",
	"HORSEA",
	"SEADRA",
	"GOLDEEN",
	"SEAKING",
	"STARYU",
	"STARMIE",
	"MR. MIME",
	"SCYTHER",
	"JYNX",
	"ELECTABUZZ",
	"MAGMAR",
	"PINSIR",
	"TAUROS",
	"MAGIKARP",
	"GYARADOS",
	"LAPRAS",
	"DITTO",
	"EEVEE",
	"VAPOREON",
	"JOLTEON",
	"FLAREON",
	"PORYGON",
	"OMANYTE",
	"OMASTAR",
	"KABUTO",
	"KABUTOPS",
	"AERODACTYL",
	"SNORLAX",
	"ARTICUNO",
	"ZAPDOS",
	"MOLTRES",
	"DRATINI",
	"DRAGONAIR",
	"DRAGONITE",
	"MEWTWO",
	"MEW"
]
const GEN2_LABELS: Array[String] = [
	"BULBASAUR",
	"IVYSAUR",
	"VENUSAUR",
	"CHARMANDER",
	"CHARMELEON",
	"CHARIZARD",
	"SQUIRTLE",
	"WARTORTLE",
	"BLASTOISE",
	"CATERPIE",
	"METAPOD",
	"BUTTERFREE",
	"WEEDLE",
	"KAKUNA",
	"BEEDRILL",
	"PIDGEY",
	"PIDGEOTTO",
	"PIDGEOT",
	"RATTATA",
	"RATICATE",
	"SPEAROW",
	"FEAROW",
	"EKANS",
	"ARBOK",
	"PIKACHU",
	"RAICHU",
	"SANDSHREW",
	"SANDSLASH",
	"NIDORAN♀",
	"NIDORINA",
	"NIDOQUEEN",
	"NIDORAN♂",
	"NIDORINO",
	"NIDOKING",
	"CLEFAIRY",
	"CLEFABLE",
	"VULPIX",
	"NINETALES",
	"JIGGLYPUFF",
	"WIGGLYTUFF",
	"ZUBAT",
	"GOLBAT",
	"ODDISH",
	"GLOOM",
	"VILEPLUME",
	"PARAS",
	"PARASECT",
	"VENONAT",
	"VENOMOTH",
	"DIGLETT",
	"DUGTRIO",
	"MEOWTH",
	"PERSIAN",
	"PSYDUCK",
	"GOLDUCK",
	"MANKEY",
	"PRIMEAPE",
	"GROWLITHE",
	"ARCANINE",
	"POLIWAG",
	"POLIWHIRL",
	"POLIWRATH",
	"ABRA",
	"KADABRA",
	"ALAKAZAM",
	"MACHOP",
	"MACHOKE",
	"MACHAMP",
	"BELLSPROUT",
	"WEEPINBELL",
	"VICTREEBEL",
	"TENTACOOL",
	"TENTACRUEL",
	"GEODUDE",
	"GRAVELER",
	"GOLEM",
	"PONYTA",
	"RAPIDASH",
	"SLOWPOKE",
	"SLOWBRO",
	"MAGNEMITE",
	"MAGNETON",
	"FARFETCH'D",
	"DODUO",
	"DODRIO",
	"SEEL",
	"DEWGONG",
	"GRIMER",
	"MUK",
	"SHELLDER",
	"CLOYSTER",
	"GASTLY",
	"HAUNTER",
	"GENGAR",
	"ONIX",
	"DROWZEE",
	"HYPNO",
	"KRABBY",
	"KINGLER",
	"VOLTORB",
	"ELECTRODE",
	"EXEGGCUTE",
	"EXEGGUTOR",
	"CUBONE",
	"MAROWAK",
	"HITMONLEE",
	"HITMONCHAN",
	"LICKITUNG",
	"KOFFING",
	"WEEZING",
	"RHYHORN",
	"RHYDON",
	"CHANSEY",
	"TANGELA",
	"KANGASKHAN",
	"HORSEA",
	"SEADRA",
	"GOLDEEN",
	"SEAKING",
	"STARYU",
	"STARMIE",
	"MR. MIME",
	"SCYTHER",
	"JYNX",
	"ELECTABUZZ",
	"MAGMAR",
	"PINSIR",
	"TAUROS",
	"MAGIKARP",
	"GYARADOS",
	"LAPRAS",
	"DITTO",
	"EEVEE",
	"VAPOREON",
	"JOLTEON",
	"FLAREON",
	"PORYGON",
	"OMANYTE",
	"OMASTAR",
	"KABUTO",
	"KABUTOPS",
	"AERODACTYL",
	"SNORLAX",
	"ARTICUNO",
	"ZAPDOS",
	"MOLTRES",
	"DRATINI",
	"DRAGONAIR",
	"DRAGONITE",
	"MEWTWO",
	"MEW",
	"CHIKORITA",
	"BAYLEEF",
	"MEGANIUM",
	"CYNDAQUIL",
	"QUILAVA",
	"TYPHLOSION",
	"TOTODILE",
	"CROCONAW",
	"FERALIGATR",
	"SENTRET",
	"FURRET",
	"HOOTHOOT",
	"NOCTOWL",
	"LEDYBA",
	"LEDIAN",
	"SPINARAK",
	"ARIADOS",
	"CROBAT",
	"CHINCHOU",
	"LANTURN",
	"PICHU",
	"CLEFFA",
	"IGGLYBUFF",
	"TOGEPI",
	"TOGETIC",
	"NATU",
	"XATU",
	"MAREEP",
	"FLAAFFY",
	"AMPHAROS",
	"BELLOSSOM",
	"MARILL",
	"AZUMARILL",
	"SUDOWOODO",
	"POLITOED",
	"HOPPIP",
	"SKIPLOOM",
	"JUMPLUFF",
	"AIPOM",
	"SUNKERN",
	"SUNFLORA",
	"YANMA",
	"WOOPER",
	"QUAGSIRE",
	"ESPEON",
	"UMBREON",
	"MURKROW",
	"SLOWKING",
	"MISDREAVUS",
	"UNOWN",
	"WOBBUFFET",
	"GIRAFARIG",
	"PINECO",
	"FORRETRESS",
	"DUNSPARCE",
	"GLIGAR",
	"STEELIX",
	"SNUBBULL",
	"GRANBULL",
	"QWILFISH",
	"SCIZOR",
	"SHUCKLE",
	"HERACROSS",
	"SNEASEL",
	"TEDDIURSA",
	"URSARING",
	"SLUGMA",
	"MAGCARGO",
	"SWINUB",
	"PILOSWINE",
	"CORSOLA",
	"REMORAID",
	"OCTILLERY",
	"DELIBIRD",
	"MANTINE",
	"SKARMORY",
	"HOUNDOUR",
	"HOUNDOOM",
	"KINGDRA",
	"PHANPY",
	"DONPHAN",
	"PORYGON2",
	"STANTLER",
	"SMEARGLE",
	"TYROGUE",
	"HITMONTOP",
	"SMOOCHUM",
	"ELEKID",
	"MAGBY",
	"MILTANK",
	"BLISSEY",
	"RAIKOU",
	"ENTEI",
	"SUICUNE",
	"LARVITAR",
	"PUPITAR",
	"TYRANITAR",
	"LUGIA",
	"HO-OH",
	"CELEBI"
]

func register(host: Gen2ModHost, manifest: PokeModManifest) -> void:
	var generation: int = host.generation()
	var max_species: int = 151 if generation == 1 else 251
	var labels: Array[String] = GEN1_LABELS if generation == 1 else GEN2_LABELS
	var values: Array[int] = []
	for number: int in range(1, max_species + 1):
		values.append(number)

	host.register_option(manifest.id, {
		"key": ENABLED_KEY,
		"label": "WILD ENCOUNTERS",
		"values": [false, true],
		"labels": ["OFF", "ON"],
		"default": false,
	})
	host.register_option(manifest.id, {
		"key": SPECIES_KEY,
		"label": "POKEMON",
		"values": values,
		"labels": labels,
		"default": 1,
	})

	host.option_changed.connect(
		func(mod: StringName, key: StringName, value: Variant) -> void:
			if mod == manifest.id and (key == ENABLED_KEY or key == SPECIES_KEY):
				_apply(host, manifest.id, key, value)
	)

	_apply(host, manifest.id)

func _effective_option(host: Gen2ModHost, id: StringName, wanted_key: StringName, changed_key: StringName, changed_value: Variant) -> Variant:
	if wanted_key == changed_key:
		return changed_value
	return host.option(id, wanted_key)

func _apply(host: Gen2ModHost, id: StringName, changed_key: StringName = &"", changed_value: Variant = null) -> void:
	# First remove only this mod's wild-table patches. OFF therefore means vanilla.
	host.clear_patches(id, Gen2ContentOverlay.KIND_ENCOUNTER)
	if not bool(_effective_option(host, id, ENABLED_KEY, changed_key, changed_value)):
		return

	var species: int = int(_effective_option(host, id, SPECIES_KEY, changed_key, changed_value))
	var max_species: int = 151 if host.generation() == 1 else 251
	if species < 1 or species > max_species:
		return

	if _data == null:
		_data = GameData.open(host.target_game())
	if _data == null:
		return

	for map: Gen2WorldMap in _data.world_maps():
		for method: StringName in Gen2ContentOverlay.ENCOUNTER_METHODS:
			var row: Dictionary = _data.world_encounter(method, map.group, map.number)
			if not row.is_empty():
				host.patch_encounter(id, method, map.group, map.number, {
					"slots": _replace_species(row["slots"], species),
				})

func _replace_species(slots: Array, species: int) -> Array:
	var out: Array = []
	for slot: Variant in slots:
		if slot is Array:
			out.append(_replace_species(slot, species))
		else:
			# Deliberately preserve the cartridge's level. Only species changes.
			out.append({
				"species": species,
				"level": int((slot as Dictionary)["level"]),
			})
	return out
